metadata.format.version = "1.1"

[versions]
# Error Tracking
sentry = "6.18.0"

[libraries]
# Error Tracking
sentry = { group = "io.sentry", name = "sentry", version.ref = "sentry" }
sentryJul = { group = "io.sentry", name = "sentry-jul", version.ref = "sentry" }

[bundles]


[plugins]

