name: "Merge Request"
description: "Create a merge request to merge your changes into the cli project"
body:
  - type: textarea
    attributes:
      label: Describe the changes
      description: |
        A clear and concise description of what changes you are making.
        If you have a screenshot of the changes, please attach it below.
      validations:
        required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the merge request here
  - type: checkboxes
    attributes:
      label: Checklist
      description: |
        Before submitting your merge request, please make sure you have done the following:
        - [ ] I have read the CONTRIBUTING.md document
        - [ ] I have tested my changes locally
        - [ ] I have added tests to cover my changes
        - [ ] I have updated the documentation
        - [ ] I have added the necessary labels
      validations:
        required: true